"""Add trip, destination, itinerary_day, activity, meal, accommodation, transportation tables

Revision ID: 1356a9a19d09
Revises: fcb8320e89ee
Create Date: 2026-03-22 21:28:33.615118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1356a9a19d09'
down_revision: Union[str, None] = 'fcb8320e89ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNING', 'PLANNED', 'FINISHED', name='tripstatus'), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('travelers_adults', sa.Integer(), nullable=False),
    sa.Column('travelers_children', sa.Integer(), nullable=False),
    sa.Column('travelers_infants', sa.Integer(), nullable=False),
    sa.Column('travel_style', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('pace_preference', sa.String(length=100), nullable=True),
    sa.Column('accommodation_type', sa.String(length=100), nullable=True),
    sa.Column('budget_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_currency', sa.String(length=3), nullable=True),
    sa.Column('budget_accommodation', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_food', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_activities', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_transportation', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_other', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ai_weather_forecast', sa.Text(), nullable=True),
    sa.Column('ai_local_tips', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    op.create_table('accommodations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=True),
    sa.Column('check_out', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('price_per_night', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amenities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('check_in_time', sa.String(length=10), nullable=True),
    sa.Column('check_out_time', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accommodations_id'), 'accommodations', ['id'], unique=False)
    op.create_index(op.f('ix_accommodations_trip_id'), 'accommodations', ['trip_id'], unique=False)
    op.create_table('destinations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=150), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('departure_date', sa.Date(), nullable=True),
    sa.Column('nights_staying', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinations_id'), 'destinations', ['id'], unique=False)
    op.create_index(op.f('ix_destinations_trip_id'), 'destinations', ['trip_id'], unique=False)
    op.create_table('transportations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('from_location', sa.String(length=512), nullable=True),
    sa.Column('to_location', sa.String(length=512), nullable=True),
    sa.Column('from_city', sa.String(length=150), nullable=True),
    sa.Column('to_city', sa.String(length=150), nullable=True),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('flight_number', sa.String(length=50), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('booking_reference', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transportations_id'), 'transportations', ['id'], unique=False)
    op.create_index(op.f('ix_transportations_trip_id'), 'transportations', ['trip_id'], unique=False)
    op.create_table('itinerary_days',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerary_days_destination_id'), 'itinerary_days', ['destination_id'], unique=False)
    op.create_index(op.f('ix_itinerary_days_id'), 'itinerary_days', ['id'], unique=False)
    op.create_index(op.f('ix_itinerary_days_trip_id'), 'itinerary_days', ['trip_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('itinerary_day_id', sa.UUID(), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('booking_required', sa.Boolean(), nullable=False),
    sa.Column('booking_url', sa.String(length=512), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('location_address', sa.String(length=512), nullable=True),
    sa.Column('location_city', sa.String(length=150), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['itinerary_day_id'], ['itinerary_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_index(op.f('ix_activities_itinerary_day_id'), 'activities', ['itinerary_day_id'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('itinerary_day_id', sa.UUID(), nullable=False),
    sa.Column('time', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('restaurant_name', sa.String(length=255), nullable=False),
    sa.Column('cuisine', sa.String(length=100), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('location_address', sa.String(length=512), nullable=True),
    sa.Column('location_city', sa.String(length=150), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['itinerary_day_id'], ['itinerary_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_id'), 'meals', ['id'], unique=False)
    op.create_index(op.f('ix_meals_itinerary_day_id'), 'meals', ['itinerary_day_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meals_itinerary_day_id'), table_name='meals')
    op.drop_index(op.f('ix_meals_id'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_activities_itinerary_day_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_itinerary_days_trip_id'), table_name='itinerary_days')
    op.drop_index(op.f('ix_itinerary_days_id'), table_name='itinerary_days')
    op.drop_index(op.f('ix_itinerary_days_destination_id'), table_name='itinerary_days')
    op.drop_table('itinerary_days')
    op.drop_index(op.f('ix_transportations_trip_id'), table_name='transportations')
    op.drop_index(op.f('ix_transportations_id'), table_name='transportations')
    op.drop_table('transportations')
    op.drop_index(op.f('ix_destinations_trip_id'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_id'), table_name='destinations')
    op.drop_table('destinations')
    op.drop_index(op.f('ix_accommodations_trip_id'), table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_id'), table_name='accommodations')
    op.drop_table('accommodations')
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
