"""Revert JSON back to ARRAY

Revision ID: e5f41161a19b
Revises: c20ea422a072
Create Date: 2026-03-22 21:58:22.693411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5f41161a19b'
down_revision: Union[str, None] = 'c20ea422a072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accommodations', 'amenities',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               postgresql_using="translate(amenities::text, '[]', '{}')::varchar[]")
    op.alter_column('trips', 'travel_style',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               postgresql_using="translate(travel_style::text, '[]', '{}')::varchar[]")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'travel_style',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('accommodations', 'amenities',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
