"""Add role to user table

Revision ID: fcb8320e89ee
Revises: 48dd32e2a1c4
Create Date: 2026-03-18 00:16:42.457363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb8320e89ee'
down_revision: Union[str, None] = '48dd32e2a1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    userrole_enum = sa.Enum('USER', 'ADMIN', name='userrole')
    userrole_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', userrole_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    userrole_enum = sa.Enum('USER', 'ADMIN', name='userrole')
    userrole_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
